import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { AvailablePetsAutogeneratedClientComponent } from './available-pets-autogenerated-client/available-pets-autogenerated-client.component';
import { AvailablePetsComponent } from './available-pets/available-pets.component';

const routes: Routes = [
  { path: '', component: AvailablePetsComponent },
  { path: 'auto-generated-client', component: AvailablePetsAutogeneratedClientComponent },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
