// Core
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

// Comps and modules
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AvailablePetsComponent } from './available-pets/available-pets.component';
import { AvailablePetsAutogeneratedClientComponent } from './available-pets-autogenerated-client/available-pets-autogenerated-client.component';

// Third party
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { HttpClientModule } from '@angular/common/http';
// import { ApiModule as PetstoreApiModule } from '@ajpgross/petstore-client';

@NgModule({
  declarations: [
    AppComponent,
    AvailablePetsComponent,
    AvailablePetsAutogeneratedClientComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    NgbModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
