import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { PetService, Pet as IPet, BASE_PATH } from '@ajpgross/petstore-client';
import { environment } from 'src/environments/environment';

@Component({
  selector: 'app-available-pets-autogenerated-client',
  templateUrl: './available-pets-autogenerated-client.component.html',
  providers: [
    { provide: BASE_PATH, useValue: environment.apiRoot }
  ]
})
export class AvailablePetsAutogeneratedClientComponent implements OnInit {

  public availablePets: IPet[] = [];
  public soldPets: IPet[] = [];

  public links = [
    { title: 'Available Pets', fragment: 'available' },
    { title: 'Sold Pets', fragment: 'sold' }
  ];

  constructor(public route: ActivatedRoute, private petsService: PetService) { }

  ngOnInit(): void {
    this.petsService.findPetsByStatus('available')
      .subscribe((pets: IPet[]) => this.availablePets = pets);

    this.petsService.findPetsByStatus('sold')
      .subscribe((pets: IPet[]) => this.soldPets = pets);
  }
}
